//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.7
// source: filter.proto

package proto

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const WasmSchedulingPluginAPIVersion = 1

//export wasm_scheduling_api_version
func _wasm_scheduling_api_version() uint64 {
	return WasmSchedulingPluginAPIVersion
}

var wasmScheduling WasmScheduling

func RegisterWasmScheduling(p WasmScheduling) {
	wasmScheduling = p
}

//export wasm_scheduling_filter
func _wasm_scheduling_filter(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req FilterRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := wasmScheduling.Filter(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
